import { maxVst3WorkerEventsPerBlock } from "@daw-browser/plugin-host-protocol"
import { z } from "zod"

const runtimeFaultSchemaV2 = z.object({
  kind: z.enum(["compressor", "owned-processor", "track-meter", "recorder"]),
  codePresent: z.boolean(),
}).strict()
const runtimeFaultSnapshotSchemaV2 = z.object({
  eventCount: z.number().int().nonnegative(),
  uniqueSignatureCount: z.number().int().nonnegative(),
  byKind: z.object({
    compressor: z.number().int().nonnegative(),
    "owned-processor": z.number().int().nonnegative(),
    "track-meter": z.number().int().nonnegative(),
    recorder: z.number().int().nonnegative(),
  }).strict(),
    last: runtimeFaultSchemaV2.nullable(),
}).strict()
export const desktopDiagnosticsSchemaV2 = z.object({
  version: z.literal("v2"),
  scheduler: z.object({
    progressCount: z.number().int().nonnegative(),
    compileCount: z.number().int().nonnegative(),
    compileTotalMs: z.number().finite().nonnegative(),
    compileMaxMs: z.number().finite().nonnegative(),
    submittedVstSegments: z.number().int().nonnegative(),
  }).strict().optional(),
  audio: z.object({
    state: z.enum(["suspended", "running", "closed", "uninitialized"]),
    sampleRate: z.number().finite().nullable(),
    requestedSampleRate: z.number().finite().nullable(),
    latencyHint: z.union([z.enum(["balanced", "interactive", "playback"]), z.number().finite()]).nullable(),
    baseLatencySec: z.number().finite().nonnegative().nullable(),
    outputLatencySec: z.number().finite().nonnegative().nullable(),
    totalOutputLatencySec: z.number().finite().nonnegative().nullable(),
    graphPdcLatencyFrames: z.number().int().nonnegative().nullable(),
    workletFaultCount: z.number().int().nonnegative(),
    runtimeFaults: runtimeFaultSnapshotSchemaV2,
    inferredApplicationStallCount: z.number().int().nonnegative(),
  }).strict(),
  recording: z.object({
    requestedFormat: z.enum(["pcm", "compressed"]),
    activeFormat: z.enum(["pcm", "compressed"]),
    requestedLayout: z.enum(["mono", "stereo"]),
    activeChannels: z.number().int().positive().nullable(),
    requestedSampleRate: z.number().finite().positive().nullable(),
    activeSampleRate: z.number().finite().positive().nullable(),
    transport: z.enum(["sab", "transferable"]).nullable(),
    capturedFrames: z.number().int().nonnegative().nullable(),
    overrunFrames: z.number().int().nonnegative().nullable(),
    droppedFrames: z.number().int().nonnegative().nullable(),
    queuedFrames: z.number().int().nonnegative().nullable(),
    peakQueuedFrames: z.number().int().nonnegative(),
    writerReturnedBuffers: z.number().int().nonnegative(),
    writerOutstandingBuffers: z.number().int().min(0).max(8),
    nativeReceivedBlocks: z.number().int().nonnegative(),
    nativeArrivalGapMaxMs: z.number().finite().nonnegative(),
    nativeHandlerMaxMs: z.number().finite().nonnegative(),
    peakWriterOutstandingBuffers: z.number().int().min(0).max(8),
    sabWriterOccupancy: z.number().int().min(0).max(8).optional(),
    peakSabWriterOccupancy: z.number().int().min(0).max(8).optional(),
    writerReturnMaxMs: z.number().finite().nonnegative(),
    writerReturnDeliveryMaxMs: z.number().finite().nonnegative(),
    writerReturnDeliveryWorst: z.object({
      returnedAtEpochMs: z.number().finite().nonnegative().max(Number.MAX_SAFE_INTEGER),
      receivedAtEpochMs: z.number().finite().nonnegative().max(Number.MAX_SAFE_INTEGER),
    }).strict().refine((value) => value.receivedAtEpochMs >= value.returnedAtEpochMs).nullable(),
    writerOldestOutstandingMs: z.number().finite().nonnegative(),
    writerTiming: z.object({
      append: z.object({
        count: z.number().int().nonnegative(),
        startDelayMs: z.object({ total: z.number().finite().nonnegative(), max: z.number().finite().nonnegative() }).strict(),
        durationMs: z.object({ total: z.number().finite().nonnegative(), max: z.number().finite().nonnegative() }).strict(),
      }).strict(),
      storage: z.object({
        headerWriteMs: z.object({ count: z.number().int().nonnegative(), total: z.number().finite().nonnegative(), max: z.number().finite().nonnegative() }).strict(),
        channelWriteMs: z.object({ count: z.number().int().nonnegative(), total: z.number().finite().nonnegative(), max: z.number().finite().nonnegative() }).strict(),
      }).strict().nullable(),
    }).strict().nullable(),
    muted: z.boolean(),
    deviceLost: z.boolean(),
    lastFailurePresent: z.boolean(),
    termination: z.object({
      cause: z.enum(["native-fatal", "writer-failure", "lifecycle-cancellation", "controller-cleanup", "explicit-stop", "start-failure", "capture-failure"]),
    }).strict().nullable(),
    lifecycleTransitions: z.array(z.string().max(64)).max(8),
    lastNativeStatus: z.object({
      active: z.boolean(),
      fatal: z.boolean(),
      capturedFrames: z.number().int().nonnegative(),
      droppedFrames: z.number().int().nonnegative(),
      queuedBlocks: z.number().int().nonnegative(),
    }).strict().nullable(),
  }).strict(),
  counts: z.object({
    tracks: z.number().int().nonnegative(),
    clips: z.number().int().nonnegative(),
  }).strict(),
  waveform: z.object({
    available: z.literal(false),
    reason: z.literal("not-exposed-at-controller-boundary"),
  }).strict(),
  native: z.discriminatedUnion("status", [
    z.object({
      status: z.literal("unavailable"),
      reason: z.literal("desktop-bridge-unavailable"),
    }).strict(),
    z.object({
      status: z.literal("failed"),
      errorCode: z.literal("native-diagnostics-unavailable"),
      artifactVerification: z.union([
        z.object({ status: z.enum(["disabled", "development", "verified"]) }).strict(),
        z.object({ status: z.literal("failed") }).strict(),
      ]),
    }).strict(),
    z.object({
      status: z.literal("available"),
      artifactVerification: z.union([
        z.object({ status: z.enum(["disabled", "development", "verified"]) }).strict(),
        z.object({ status: z.literal("failed") }).strict(),
      ]),
      diagnostics: z.object({
      workerAutomation: z.object({
        instanceId: z.string().min(1).max(256),
        acceptedPoints: z.number().int().positive().max(maxVst3WorkerEventsPerBlock),
        lastParameterId: z.number().int().nonnegative().max(0xffffffff),
        transportEpoch: z.number().int().positive().max(0xffffffff),
        sequence: z.string().regex(/^[1-9][0-9]*$/),
      }).strict().nullable(),
      transportFrame: z.string().regex(/^-?(0|[1-9][0-9]*)$/).optional(),
      realtimePerformance: z.object({
        sampleRateHz: z.number().int().nonnegative().max(384_000),
        framesPerCallback: z.number().int().nonnegative().max(8_192),
        observationCount: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingP50Nanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingP95Nanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingP99Nanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingMaximumNanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        deadlineMisses: z.string().regex(/^(0|[1-9][0-9]*)$/),
      }).strict().optional(),
      vstWorkerPerformance: z.object({
        activeWorkers: z.number().int().nonnegative().max(64),
        observationCount: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingP50Nanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingP95Nanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingP99Nanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        processingMaximumNanoseconds: z.string().regex(/^(0|[1-9][0-9]*)$/),
        deadlineMisses: z.string().regex(/^(0|[1-9][0-9]*)$/),
        watchdogMisses: z.string().regex(/^(0|[1-9][0-9]*)$/),
        faults: z.string().regex(/^(0|[1-9][0-9]*)$/),
        restarts: z.string().regex(/^(0|[1-9][0-9]*)$/),
      }).strict().optional(),
      state: z.enum(["idle", "configured", "running", "faulted"]),
      activeRevision: z.number().int().nonnegative(),
      preparedRevision: z.number().int().nonnegative(),
      retiredRevision: z.number().int().nonnegative(),
      transportEpoch: z.number().int().nonnegative(),
      renderEpoch: z.string().regex(/^(0|[1-9][0-9]*)$/),
      installedAssets: z.number().int().nonnegative(),
      callbacks: z.number().int().nonnegative(),
      rejectedBlocks: z.number().int().nonnegative(),
      lastRejectedReason: z.number().int().nonnegative(),
      lastRejectedCallback: z.string().regex(/^(0|[1-9][0-9]*)$/),
      lastRejectedRenderEpoch: z.string().regex(/^(0|[1-9][0-9]*)$/),
      lastRejectedTransportEpoch: z.number().int().nonnegative(),
      lastRejectedCoreResult: z.number().int().nonnegative(),
      lastRejectedFrameCount: z.number().int().nonnegative(),
      lastRejectedChannelCount: z.number().int().nonnegative(),
      lastRejectedProcessorEventCount: z.number().int().nonnegative(),
      lastRejectedInstrumentEventCount: z.number().int().nonnegative(),
      lastRejectedGraphRevision: z.number().int().nonnegative(),
      }).strict().refine(value => value.workerAutomation === null
        || value.workerAutomation.transportEpoch === value.transportEpoch, "Stale worker automation epoch"),
    }).strict(),
  ]),
}).strict()
