import { expect, test } from 'bun:test'
import { portableAudioCoreWorklet } from './worklet-manifest'

const publicRoot = new URL('../../../public/', import.meta.url)

test('portable Wasm worklet defers initialization and keeps process allocation-free', async () => {
  const worklet = await Bun.file(new URL(portableAudioCoreWorklet.modulePath, publicRoot)).text()
  const source = await Bun.file(new URL('audio-worklets/daw-portable-audio-core-host-v1.js', publicRoot)).text()
  const processStart = source.indexOf('  process(inputs, outputs)')
  const processBody = source.slice(processStart, source.indexOf('\n  }\n}', processStart))
  expect(worklet).toContain("import { DawPortableAudioCoreHost } from './daw-portable-audio-core-host-v1.js'")
  expect(worklet).toContain('return this.host.process(inputs, outputs)')
  expect(worklet).toContain('options.processorOptions.wasmModule')
  expect(worklet).toContain('{ ...event.data, wasmModule: this.wasmModule }')
  expect(source).toContain('WebAssembly.instantiate(message.wasmModule)')
  expect(processBody).not.toContain('WebAssembly.')
  expect(processBody).not.toContain('new ')
  expect(processBody).not.toContain("type: 'recording-capture-")
  expect(processBody).toContain('this.postMessage(this.recordingCaptureAvailableMessage)')
  expect(processBody).not.toContain('console.')
  expect(processBody).toContain('const frames = output[0] ? output[0].length : 0')
  expect(processBody).toContain('this.coreProcess(frames')
  expect(source).toContain('daw_audio_core_wasm_graph_prepare')
  expect(source).toContain('daw_audio_core_wasm_graph_process')
  expect(source).toContain('daw_audio_core_wasm_graph_schedule_sample_source')
  expect(source).toContain('daw_audio_core_wasm_recording_capture_initialize')
  expect(source).toContain('recording-capture-diagnostics')
  expect(source).toContain("type: 'sources-scheduled'")
})

test('portable worklet writes the native graph v3 node layout and bounded installed schedules', async () => {
  const source = await Bun.file(new URL('audio-worklets/daw-portable-audio-core-host-v1.js', publicRoot)).text()
  const graphEnvelopeSource = await Bun.file(new URL('audio-worklets/daw-portable-graph-envelope-v3.js', publicRoot)).text()
  const materializeStart = source.indexOf('  materializeSchedule(startFrame, frameCount)')
  const materializeBody = source.slice(materializeStart, source.indexOf('\n  process(inputs, outputs)', materializeStart))
  expect(source).toContain('const GRAPH_ENVELOPE_VERSION = 3')
  expect(source).toContain("from './daw-portable-graph-envelope-v3.js'")
  expect(graphEnvelopeSource).toContain('offset + 108, BigInt(mixer ? mixer.instanceId : 0)')
  expect(source).toContain('snapshot.nodes.length * 132')
  expect(source).toContain("message.type === 'install-schedule'")
  expect(source).toContain("type: 'schedule-installed'")
  expect(source).toContain('this.scheduleEventOffset = exports.malloc(4 + 256 * 20)')
  expect(source).toContain('this.scheduleInstrumentEventOffset = exports.malloc(4 + 256 * 48)')
  expect(materializeBody).not.toContain('this.schedule.events')
  expect(materializeBody).not.toContain('stableId(')
  expect(materializeBody).not.toContain('BigInt(')
  expect(materializeBody).toContain('stream.cursor')
  expect(materializeBody).toContain('this.scheduleInstrumentCursor')
  expect(source).toContain('const busesToWrite = Math.max(stagedInputBusCount, this.stagedInputBusCount)')
  expect(source).not.toContain('for (let bus = 0; bus < MAX_INPUT_BUSES; bus += 1)')
})
