export const PROJECT_MANIFEST_SCHEMA_VERSION = 4
export const SUPPORTED_PROJECT_MANIFEST_SCHEMA_VERSIONS: readonly number[] = [
  1,
  2,
  3,
  PROJECT_MANIFEST_SCHEMA_VERSION,
]

export const LOCAL_PROJECT_SCHEMA_VERSION = 2
export const LOCAL_PROJECT_INDEXED_DB_VERSION = 6

export const PROJECT_PERSISTENCE_VERSIONS = {
  manifest: {
    current: PROJECT_MANIFEST_SCHEMA_VERSION,
    supported: SUPPORTED_PROJECT_MANIFEST_SCHEMA_VERSIONS,
  },
  localProject: {
    schema: LOCAL_PROJECT_SCHEMA_VERSION,
    indexedDb: LOCAL_PROJECT_INDEXED_DB_VERSION,
  },
} as const
