/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DspCharacterizationRouteImport } from './routes/dsp-characterization'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'

const DspCharacterizationRoute = DspCharacterizationRouteImport.update({
  id: '/dsp-characterization',
  path: '/dsp-characterization',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/about': typeof AboutRoute
  '/dsp-characterization': typeof DspCharacterizationRoute
  '/oauth/consent': typeof OauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/about': typeof AboutRoute
  '/dsp-characterization': typeof DspCharacterizationRoute
  '/oauth/consent': typeof OauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/about': typeof AboutRoute
  '/dsp-characterization': typeof DspCharacterizationRoute
  '/oauth/consent': typeof OauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/about'
    | '/dsp-characterization'
    | '/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Login' | '/about' | '/dsp-characterization' | '/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/about'
    | '/dsp-characterization'
    | '/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AboutRoute: typeof AboutRoute
  DspCharacterizationRoute: typeof DspCharacterizationRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/dsp-characterization': {
      id: '/dsp-characterization'
      path: '/dsp-characterization'
      fullPath: '/dsp-characterization'
      preLoaderRoute: typeof DspCharacterizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AboutRoute: AboutRoute,
  DspCharacterizationRoute: DspCharacterizationRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
